import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  base: './', // relative, so it works on any github.io project path
  plugins: [react()],
  // catalog.json lives in ../catalog (generated by catalog/build_catalog.py)
  server: { fs: { allow: ['..'] } },
});
